version: '3.0'
services:
  s3_callback:
    # Simple flask app that processes s3 callbacks.
    hostname: s3_callback
    container_name: s3_callback
    build:
      context: ./flask_callback
    ports:
      - 45000:5000
  adminer:
    # Database management in a single PHP file.
    # For looking at the indexing database.s
    container_name: mdf_adminer
    image: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: "mysql"
      ADMINER_DEFAULT_USER: "mdf_indexer_user"
      ADMINER_DEFAULT_PASS: "mdf_indexer_pass"
      ADMINER_DEFAULT_DB: "mdf_database"
    ports:
      - 43307:8080
  jupyter:
    container_name: mdf_jupyter
    image: jupyter/scipy-notebook:latest
    ports:
    - 48888:8888/tcp
    volumes:
    - ./data:/data:rw
    - .:/home/jovyan:rw
  minio:
    # Minio Server
    command: server /data
    container_name: mdf_minio
    environment:
      # minio access setup.
      MINIO_ACCESS_KEY: mdf_minio_access_key
      MINIO_SECRET_KEY: mdf_minio_secret_key
     
      MINIO_NOTIFY_WEBHOOK_ENABLE_target1: "on"
      MINIO_NOTIFY_WEBHOOK_AUTH_TOKEN: "webhook_AUTH_token"
      MINIO_NOTIFY_WEBHOOK_AUTH_TOKEN_target1: "webhook_AUTH_token"
      MINIO_NOTIFY_WEBHOOK_ENDPOINT_target1: "http://s3_callback:5000/minio_notify_webhook_endpoint/"
      MINIO_LOGGER_WEBHOOK_ENABLE_target1: "on"
      MINIO_LOGGER_WEBHOOK_AUTH_TOKEN: "logger_AUTH_token"
      MINIO_LOGGER_WEBHOOK_AUTH_TOKEN_target1: "logger_AUTH_token_target1"
      MINIO_LOGGER_WEBHOOK_ENDPOINT_target1: "http://s3_callback:5000/minio_logger_webhook_endpoint/"
      MINIO_AUDIT_WEBHOOK_ENABLE_target1: "on"
      MINIO_AUDIT_WEBHOOK_AUTH_TOKEN_target1: "audit_AUTH_token"
      MINIO_AUDIT_WEBHOOK_ENDPOINT_target1: "http://s3_callback:5000/minio_audit_webhook_endpoint/"
    hostname: mdf_minio
    image: minio/minio:latest
    ports:
    - 49000:9000/tcp
    restart: always
    volumes:
    - ./minio_config:/root/.minio:rw
    - ./mdf_data:/data:rw
  mysql:
    container_name: mdf_mysql
    environment:
      MYSQL_DATABASE: mdf_database
      MYSQL_PASSWORD: mdf_indexer_pass
      MYSQL_ROOT_PASSWORD: mdf_indexer_root_password
      MYSQL_USER: mdf_indexer_user
    image: mysql:latest
    ports:
    - 43306:3306/tcp
    restart: always
    volumes:
    - ./mysql_db_data:/var/lib/mysql:rw
  redis:
    command: redis-server
    container_name: mdf_redis
    hostname: mdf_redis
    image: redis:latest
    ports:
    - 46379:6379/tcp
    restart: always
  rq_dashboard:
    container_name: mdf_rq_dashboard
    hostname: mdf_rq_dashboard
    image: eoranged/rq-dashboard
    ports:
    - 49181:9181
    environment:
      RQ_DASHBOARD_REDIS_URL: redis://redis:6379
